---
config:
   layout: elk
   theme: neo
   look: neo
---

flowchart LR
A((1))
B((2))
C((3))
D((4))
E((5))
F((6))
G((7))
H((8))
I((9))
J((10))

A -->|0.50|G
A -->|0.50|E
B -->|1.00|B
C -->|1.00|F
D -->|1.00|D
E -->|0.50|G
E -->|0.50|A
F -->|1.00|H
G -->|1.00|E
H -->|1.00|C
I -->|0.50|A
I -->|0.50|C
J -->|0.50|E
J -->|0.50|D
